apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: {{ .Values.auth.replicas }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: {{ .Values.global.imageRegistry }}/{{ .Values.auth.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: MONGO_URI
              value: {{ .Values.auth.mongoUri | quote }}
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: {{ .Values.global.servicePort }}
      targetPort: {{ .Values.global.servicePort }}
