apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: {{ .Values.expiration.replicas }}
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: {{ .Values.global.imageRegistry }}/{{ .Values.expiration.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-srv:{{ .Values.nats.clientPort }}
            - name: NATS_CLUSTER_ID
              value: {{ .Values.nats.clusterId }}
            - name: REDIS_HOST
              value: {{ .Values.expiration.redisHost }}
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-srv
  labels:
    app: expiration
spec:
  selector:
    app: expiration
  ports:
    - name: metrics
      protocol: TCP
      port: {{ .Values.global.servicePort }}
      targetPort: {{ .Values.global.servicePort }}
