apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: {{ .Values.nats.image }}:{{ .Values.nats.imageTag }}
          args:
            - -p
            - {{ .Values.nats.clientPort | quote }}
            - -m
            - {{ .Values.nats.monitorPort | quote }}
            - -hbi
            - 5s
            - -hbt
            - 5s
            - -hbf
            - "2"
            - -SD
            - -cid
            - {{ .Values.nats.clusterId }}
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: {{ .Values.nats.clientPort }}
      targetPort: {{ .Values.nats.clientPort }}
    - name: monitoring
      protocol: TCP
      port: {{ .Values.nats.monitorPort }}
      targetPort: {{ .Values.nats.monitorPort }}
