apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: {{ .Values.orders.replicas }}
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: {{ .Values.global.imageRegistry }}/{{ .Values.orders.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-srv:{{ .Values.nats.clientPort }}
            - name: NATS_CLUSTER_ID
              value: {{ .Values.nats.clusterId }}
            - name: MONGO_URI
              value: {{ .Values.orders.mongoUri | quote }}
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
  labels:
    app: orders
spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: {{ .Values.global.servicePort }}
      targetPort: {{ .Values.global.servicePort }}
