apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: {{ .Values.payments.replicas }}
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: {{ .Values.global.imageRegistry }}/{{ .Values.payments.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-srv:{{ .Values.nats.clientPort }}
            - name: NATS_CLUSTER_ID
              value: {{ .Values.nats.clusterId }}
            - name: MONGO_URI
              value: {{ .Values.payments.mongoUri | quote }}
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.payments.image }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.global.otelExporterOtlpEndpoint }}
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
  labels:
    app: payments
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: {{ .Values.global.servicePort }}
      targetPort: {{ .Values.global.servicePort }}
